public enum VisualizationType {
    NONE,
    VERTEX_POSITIONS,
    VERTEX_VELOCITIES,
    ENERGY_GRADIENT,
    WIND_FORCE,
    STEP,
    MEASUREMENTS,
    VERTEX_MEASUREMENT_DIFF,
    VERTEX_CONSTRAINTS,
    RECON_CONSTR_MEAS_VERTEX_DESIRED_WIND_FORCE_AND_CAUSED_WIND_FORCE
}
