public enum VisualizationType {
    NONE,
    VERTEX_POSITIONS,
    VERTEX_VELOCITIES,
    ENERGY_GRADIENT,
    WIND_FORCE,
    STEP,
    MEASUREMENTS,
    VERTEX_MEASUREMENT_DIFF,
    VERTEX_CONSTRAINTS
}
